### ISSUE TITLE
Extending String with PigLatin

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#20]
_This is assignment 19 and is due on Feb 04, 2015._

Extend Ruby's String class to have a "pigatize" method that will turn any string into pig latin.

Should use the same code you wrote before, but now you are extending the String class and putting the functionality in there.

**Comment by brianburridge** [comment]
@tomwill1701 A couple things here:

1. Because you have code in this class that is executed at the bottom, I can't use your String extension in IRB (or by loading into another ruby script). To see this, go into irb and load it. You'll see what happens.

2. The method name _pigatizeString_ is a little redundant. When using it we are calling it on a String so we know it's a String method. That would be like using these method names: _splitstring_, _lengthString_, etc for all the String methods. Would be better to call it just _pigatize_.

But, it's all working good, so I'm going to close it out.

**Comment by tomwill1701** [comment]
OK.  I changed the method name.

Thanks
