### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#23]
_This is assignment 23 and is due on Feb 09, 2015._

* Create an InvoiceItem class and an Invoice class (two classes in two separate files)
* The InvoiceItem class should have the following attributes: product_name, sale_price, quantity, tax percentage
* The invoice class should have a getter and setter for an attribute called: _items_ to hold an array of all the InvoiceItems
* Create an instance method in Invoice that will calculate a total of all it's invoice items
* Use reject or select methods in order to remove any InvoiceItem objects that have a zero quantity
* Create an instance method in Invoice to sum up the invoice items and get a total
* Ask the user to enter in the attributes for each invoice item, hitting ENTER on product name when done
* With each invoice item entered, create the object and add it to the collection of invoice items within a single Invoice object.
* Then output each line item.
* Show a sub-total without the tax, then a line item for the tax, then the total.
* Bonus: make the invoice look like a real world invoice in the terminal

**Comment by tomwill1701** [comment]
Run by using main.rb < test1.txt

**Comment by brianburridge** [comment]
This looks really great.

One note, I'm not sure that line 28 is necessary. I believe if the user hits ENTER, then the name string will be `"\n"` and if you did a chomp on that it would become `""`. Therefore you would have that result but without that line. Give it a try.

**Comment by tomwill1701** [comment]
When I run it with piped input and the file hits EOF the variable "name" was set to nil.  Then with it will the .chomp failed because it complained there was no chomp method for nil.  So I removed the .chomp from the name = gets.chomp and tested for nil on the next line.

This only happened when using piped input

**Comment by brianburridge** [comment]
Ah I see.
