### ISSUE TITLE
Using Codepen

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#28]
_This is assignment 27 and is due on Feb 11, 2015._

* Sign up for an account (login with GitHub)
* [Here's mine](http://codepen.io/bburridge/)
* Create one codepen with HTML and CSS of anything. Include the link in this issue.

**Comment by tomwill1701** [comment]
http://codepen.io/tomwill1701/pen/gboxOp

**Comment by brianburridge** [comment]
A little weak, but at least you created your first one. :wink:
