### ISSUE TITLE
Improve the Movie Query app

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#31]
_This is assignment 30 and is due on Feb 16, 2015._

* Alter your existing app so you are no longer returning the synopsis in an instance variable, but instead returning the entire first movie result. We will assume for this exercise that the first movie that comes back is the one we want.
* Using all the information returned for the movie, recreate a movie information page like this one on [IMBD]() or this one on [Rotten Tomatoes](http://www.rottentomatoes.com/m/kingsman_the_secret_service/). Note it does not have to have their branding but should nicely layout as much of the movie information as possible. Ex: poster, ratings, synopsis, tomatometer, some cast, running time, etc.
* The goal is to create your own movie information page as though you were creating one for a client's movie app.

**Comment by tomwill1701** [comment]
Run using http://localhost:3000/movies/search?title=toy+story

**Comment by brianburridge** [comment]
Nice attempt to use classes to keep the functionality out of the controller. Note on the classes, we always make classes be singular. We get purals only when we have collections of multiple objects. I see you have both a _movie_ and a _movies_ class which is confusing.

:+1:
