### ISSUE TITLE
Build Pinterest

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#43]
_This is assignment 42 and is due on Mar 02, 2015._

* Should have these models: User, Pin, Board
* The home page should show "pins" from all users, and not in a table format but a grid
* Should use pagination with Kaminari on the pin page
* User should be able to create new pins, uploading an image to represent them.
* A Pin should have these attributes and belong to the user who added it: title, description, board, url, pin image
* A user should be able to create boards to pin items to. Every pin belongs to one board. A board has a name and belongs to a user.
* When the user clicks on a pin from the home page, it can either pop the pin up like Pinterest does, or go to a separate show page.
* There should be a search form to search the descriptions of the pins and show those matching (across all users).
* There should be a nav providing links to the home page, the user's pins, and the user's boards
* Bonus: make it look amazing!

**Comment by tomwill1701** [comment]
https://rocky-crag-7257.herokuapp.com

**Comment by tomwill1701** [comment]
https://github.com/tomwill1701/a42.git

**Comment by brianburridge** [comment]
@tomwill1701 I've noticed in a few of your apps now when you've created seed data, like in this one for the description, you are putting an array of sentences in the description. Can you take a look at that? It's an easy fix, but you might need to review what the Faker gem gives you back when you call it for random text.

**Comment by brianburridge** [comment]
@tomwill1701 Also, when I click on the 'Pins' button it's submitting a User request param (though not in the correct usable naming convention). Maybe that's left over and no longer used?

Other than those few tiny tweaks... :+1:

**Comment by tomwill1701** [comment]
I will work on fixing it tonight along with today's assignments




On Mar 2, 2015, at 4:40 PM, Brian Burridge <notifications@github.com<mailto:notifications@github.com>> wrote:


@tomwill1701<https://github.com/tomwill1701> Also, when I click on the 'Pins' button it's submitting a User request param (though not in the correct usable naming convention). Maybe that's left over and no longer used?

Other than those few tiny tweaks... [:+1:]
