### ISSUE TITLE
Using Memoization, Scopes, Flash, and Authorization

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#44]
_This is assignment 43 and is due on Mar 03, 2015._

* [Read about memoization](http://www.justinweiss.com/blog/2014/07/28/4-simple-memoization-patterns-in-ruby-and-one-gem/)
* Review the [ActiveRecord Scopes](http://guides.rubyonrails.org/active_record_querying.html#scopes) guide
* Review using model scopes in [ActiveAdmin](http://activeadmin.info/docs/3-index-pages.html). Scroll down to the _Index Scopes_ section
* Review my [troubleshooting guide](https://github.com/TIY-TSP-Rails-Fall2014/Assignments/blob/master/TroubleshootingGuide.md)
* Read about the [Flash](http://guides.rubyonrails.org/action_controller_overview.html#the-flash)
* Add three scopes to any model and implement in ActiveAdmin too
* Scope all your user owned models (ex. pin and board), and use within your controller so your site cannot be hacked (denying other's from accessing records they don't own).
* Add flash display on site (within layout). Use a flash notice when denying access to a record the user doesn't own. Note: once in the site wide layout, you'll want to remove the notice displays your scaffolding put in place, or you'll have them repeating on those pages.
* Add an `admin` attribute to your user model. Restrict any admin only actions from your views.

**Comment by tomwill1701** [comment]
to pin code changed:

Fixed pin index function to use normal routing url
Added current userid concept
Added pin function (pin to one of currents boards if displaying a pin not owned by current user)
Removed edit options for pins and boards if not current users
Admin column in users
fixed faker sentences to not be an array

**Comment by tomwill1701** [comment]
to existing pin application changed:

Fixed pin index function to use normal routing url
Added current userid concept
Added pin function (pin to one of current users boards if displaying a pin not owned by current user)
Removed edit options for pins and boards if not current users
Use scope to restrict access to pin and board records for update,delete,edit (show is always ok)
Admin column in users
fixed faker sentences to not be an array
scope user admin attribute in active admin

**Comment by brianburridge** [comment]
@tomwill1701 reminder, to use the `scope` syntax instead of creating methods to create scopes.

**Comment by tomwill1701** [comment]
https://rocky-crag-7257.herokuapp.com

Change code to scope instead of method

Fixed code that created existing pin to other user (old code replaced the old pin)

**Comment by brianburridge** [comment]
:+1:
