### ISSUE TITLE
Debugging a Rails Application

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#49]
_This is assignment 48 and is due on Mar 11, 2015._

* Read about ri [Up and Running With Ruby Interactive](http://samuelmullen.com/2012/01/up-and-running-with-ruby-interactive-ri/), [5 Reasons You Should Use ri To Read Ruby Documentation](http://www.jstorimer.com/blogs/workingwithcode/7766081-5-reasons-you-should-use-ri-to-read-ruby-documentation)
* Try [Dash](http://kapeli.com/dash)
* Try [OmniRef](https://www.omniref.com/)
* Sign up to use the [Suncoast Dev Slack](http://suncoast.io)
* Install the [better_errors gem](https://github.com/charliesome/better_errors) in your Pinterest application. Create an error to see how it works.
* Read about the [Rails logger](http://guides.rubyonrails.org/debugging_rails_applications.html) and implement some lines in your controller. Output an instance variable using the `.inspect` method to the log. Paste the section of your log file in a comment in this issue. In an issue comment direct me to where you have added the logger statements. (Yes, in this case you can check logger statements in).
* Read about using the [pry console debugger](https://github.com/nixme/pry-debugger) and try it in a controller action.

**Comment by tomwill1701** [comment]
Started GET "/users/79/boards" for 127.0.0.1 at 2015-03-12 14:55:14 -0400
Processing by BoardsController#index as HTML
  Parameters: {"name_prefix"=>"boards_", "user_id"=>"79"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 79]]
boad: load_parent
#<User id: 79, name: "Tom/Admin", created_at: "2015-03-03 03:55:03", updated_at: "2015-03-03 03:55:03", image: nil, admin: true>

**Comment by tomwill1701** [comment]
Started GET "/users/79/boards" for 127.0.0.1 at 2015-03-12 14:55:14 -0400
Processing by BoardsController#index as HTML
  Parameters: {"name_prefix"=>"boards_", "user_id"=>"79"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 79]]
boad: load_parent
#<User id: 79, name: "Tom/Admin", created_at: "2015-03-03 03:55:03", updated_at: "2015-03-03 03:55:03", image: nil, admin: true>

**Comment by tomwill1701** [comment]
In board_controller in load_parent method

**Comment by brianburridge** [comment]
:+1:
