### ISSUE TITLE
Rails Native Authentication

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#54]
_This is assignment 53 and is due on Mar 18, 2015._

* Review [using cookies in Rails](http://api.rubyonrails.org/classes/ActionDispatch/Cookies.html)
* Review [Rails sessions](http://guides.rubyonrails.org/action_controller_overview.html#session)
* Review [has_secure_password](http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html)
* Add real user authentication to your Pinterest app
* User sign up, sign in, sign out
* Adjust current_user method in application controller to use the signed in user from the session

**Comment by tomwill1701** [comment]
https://github.com/tomwill1701/a42

https://rocky-crag-7257.herokuapp.com

**Comment by tomwill1701** [comment]
User Joe / joe
Tom-Admin / tom

**Comment by brianburridge** [comment]
Couple things here Tom.

1. If I login with an incorrect name/password I don't see any feedback at all. It's hard to know in that case, if anything even happened.

2. If I go to a url like [this](https://rocky-crag-7257.herokuapp.com/pins/578) I get an error. Should probably either reroute to the home page if I don't have access, or, even better, show me the pin but not let me edit or delete it.

Also note for  the future, I think it's best to put sign in/out/up functionality in separate controller like a 'session' controller. Putting too much functionality into the application controller can start to become cluttered very quickly.

Could you address the first 2 and turn this again? As for the controller part, just note it for the future.

**Comment by tomwill1701** [comment]
I added a message for login failed and fixed the show pin view.  The like that allowed a user to "repin" expected a current user when it built the repin link.  Code now skips building this link if current_user not set.

I understand about a separate controller and maybe a separate view for signup also?

**Comment by tomwill1701** [comment]
I added a message for login failed and fixed the show pin view. The link that allowed a user to "repin" expected a current user when it built the repin link. Code now skips building this link if current_user not set.

I understand about a separate controller and maybe a separate view for signup also?

**Comment by brianburridge** [comment]
Ok 1 and 2 look good.

I didn't even realize that signup was the same form as the login. Yeah, that's pretty confusing.

**Comment by tomwill1701** [comment]
Yea I was lazy
Since signup only needed two items I just did it on the same form

Not real world


On Mar 20, 2015, at 1:53 PM, Brian Burridge <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok 1 and 2 look good.

I didn't even realize that signup was the same form as the login. Yeah, that's pretty confusing.

**Comment by tomwill1701** [comment]
Do I need to do anything else to get this closed?

Thanks

**Comment by brianburridge** [comment]
:+1:
