### ISSUE TITLE
Sending Email

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#57]
_This is assignment 55 and is due on Mar 24, 2015._

* Read the Rails guide on [Action Mailer](http://guides.rubyonrails.org/action_mailer_basics.html)
* Add a welcome mailer to the sign up process in your Pinterest app
* Get it working on your laptop first, using the [letter_opener gem](https://github.com/ryanb/letter_opener)
https://devcenter.heroku.com/articles/sendgrid#ruby-rails
* Next, deploy to Heroku and setup with sendgrid
* Ensure emails are being received by users when signing up on Heroku

**Comment by tomwill1701** [comment]
https://rocky-crag-7257.herokuapp.com

https://github.com/tomwill1701/a42

**Comment by brianburridge** [comment]
It works. Not a lot of originality in your email template, ahem, but it works. ;)

**Comment by tomwill1701** [comment]
Sorry.  Playing with formtastic and cocoon and filterrific.  Which was more fun than playing with the email template,  I will try and push myself more on the assignments in the future.

**Comment by brianburridge** [comment]
May as well use the opportunity, since you are completing them so quickly. :)
