### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#6]
_This assignment is due on Jan 28, 2015._

* Create a Ruby script to ask the user for their name and then wish them a Happy Birthday by name
* Add some comments to your code
* Put this code in a gist and paste the link from the gist in a comment of this issue

## Bonus
* Add another prompt for birthdate
* Show the birth date in parenthesis after the greeting
* Note: user must enter date in like: 2014/09/22 or 2014-09-22
* Change the output formatting to: Friday, April 1, 1974
* Capitalize the user's name

**Comment by tomwill1701** [comment]
https://gist.github.com/tomwill1701/87b66c75b86a3d861f50

**Comment by brianburridge** [comment]
@tomwill1701 well, you used a ton of stuff we haven't done in class yet, but I won't penalize you for it. :)

:+1:

**Comment by tomwill1701** [comment]
google is your friend.

**Comment by brianburridge** [comment]
hopefully you mean you googled how to do those things and not that you googled for a complete solution.

**Comment by tomwill1701** [comment]
Yes
Just how to trap the bad date



On Jan 27, 2015, at 2:56 PM, Brian Burridge <notifications@github.com<mailto:notifications@github.com>> wrote:


hopefully you mean you googled how to do those things and not that you googled for a complete solution.
