### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#60]
_This is assignment 59 and is due on Mar 26, 2015._

* Add a [jQuery plugin](http://plugins.jquery.com/) to your Pinterest app
* Be sure to direct me to where on your app you've added it, both in your code and what page it's running on at Heroku so I can see it work.

**Comment by tomwill1701** [comment]
Changed signin to use a modal form

Changed new/edit pin to use chosen when picking board name
used https://github.com/tsechingho/chosen-rails for chosen

**Comment by tomwill1701** [comment]
removed the chosen-rails gem.  Could not get it to work with heroku.  Installed js and css files.

https://rocky-crag-7257.herokuapp.com

**Comment by brianburridge** [comment]
@tomwill1701 you'll just need to make that turbolinks change from this morning's class to get it to work all the time. Then I can close this out.

**Comment by tomwill1701** [comment]
I added data: { no_turbolink: true } to the link for "create new pin" and it fixed the problem.
I am not sure if I did this right?  And why the same was not needed for the link to "edit pin"
The edit pin always worked but new pin did not but they render the same pages??

**Comment by brianburridge** [comment]
Ideally the best solution is to change the event for adding the chosen plugin to be on page:change instead of document ready. That should fix it in all cases.

```coffeescript
$(document).on "page:change", ->
```

**Comment by brianburridge** [comment]
Oh, and I gave you the coffeescript version, fyi.

**Comment by tomwill1701** [comment]
removed no_turbolink and change coffee to:

$ ->
  # enable chosen js
  $(document).on "page:change", ->
    $('.chosen-select').chosen
      allow_single_deselect: true
      no_results_text: 'No results matched'
      width: '200px'

**Comment by tomwill1701** [comment]
removed no_turbolink and change coffee to:

$ ->
  # enable chosen js
     $(document).on "page:change", ->
        $('.chosen-select').chosen
          allow_single_deselect: true
          no_results_text: 'No results matched'
          width: '200px'

**Comment by brianburridge** [comment]
:+1:
