### ISSUE TITLE
CoffeeScript

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#61]
_This is assignment 60 and is due on Mar 30, 2015._

* Review the Rails guide on [Working with JavaScript in Rails](http://guides.rubyonrails.org/working_with_javascript_in_rails.html)
* Refer to the [CoffeeScript docs](http://coffeescript.org/)
* Write some CoffeeScript in your Pinterest app to listen for a click on the header/logo of your app (in the nav), and when clicked, popup a bootstrap modal with some about information for your app.
* Bonus: Use Ajax in one place in your Pinterest app (deleting an item, adding an item, etc)

**Comment by tomwill1701** [comment]
https://rocky-crag-7257.herokuapp.com

Added modal when top header area is clicked.

**Comment by brianburridge** [comment]
@tomwill1701 if you click on the logo, you'll notice, that while it does popup the modal, it also leaves the site and goes to the iron yard site. You would want to use `event.preventDefault()` to stop the link from working so the user can see the modal.

**Comment by tomwill1701** [comment]
added event.preventDefault(); for modal popup

**Comment by brianburridge** [comment]
Did you see my slack comment on this?

**Comment by tomwill1701** [comment]
No, sorry

**Comment by tomwill1701** [comment]
added event variable to js and tested on firefox

**Comment by brianburridge** [comment]
Bingo. :)
