### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#7]
_This assignment is due on Jan 28, 2015._

* Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
* Run the code and paste the output into your issue as a comment for this assignment
* It should list all the proper class names and all class tests should result in 'true'
* Before you run it, can you guess what will happen with the constant code you've created?

**Comment by tomwill1701** [comment]
Toms-MacBook-Pro:code tomwilliamson$ ./a7.rb
String
Date
Fixnum
Array
Array
Hash
true
true
true
true
true
true
String
Fixnum
Array
Hash
Symbol
./a7.rb:47: warning: already initialized constant SS
./a7.rb:45: warning: previous definition of SS was here
new string
Toms-MacBook-Pro:code tomwilliamson$
