### ISSUE TITLE
Regular Expressions, Gsub, Split, Matching

### ISSUE THREAD

**Issue by brianburridge** [tomwill1701/Assignments#9]
_This assignment is due on Jan 29, 2015._

* [Read](https://www.bluebox.net/insight/blog-article/using-regular-expressions-in-ruby-part-1-of-3)
* [Review](http://lzone.de/Ruby-Regex-Examples)
* [Play](http://rubular.com/)
* Write a Ruby script to do the following:

1. Take the string "Hello World" and split it on whitespace. Show two ways to do this.
2. Use the Peter Piper tongue twister and split it on 'pick'
3. Use gsub only to change the first passage to the second in the fewest amount of commands:

    Original: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You're on your own. And you know what you know. And YOU are the one who'll decide where to go..."

    Result: "I have brains in my head. I have feet in my shoes. I can steer myself any direction I choose. I'm on my own. And I know what I know. And I'M the one who'll decide where to go..."

4. Write code to determine how many times 'sh' occurs in the following phrase:

    There once was a man who had a sister, his name was Mr. Fister. Mr. Fister's sister sold sea shells by the sea shore. Mr. Fister didn't sell sea shells, he sold silk sheets. Mr. Fister told his sister that he sold six silk sheets to six shieks. The sister of Mr. Fister said I sold six shells to six shieks too!

5. In the same phrase above, how many times does 'sh' occur when followed by an 'o'? Show the code.
6. Match the word `foot` but not `football` in this phrase: "He played football despite having an artificial foot.""
7. Match the last `sits` in a phrase using this phrase: "I saw Susie sitting in a shoe shine shop. Where she sits she shines, and where she shines she sits."

**Comment by tomwill1701** [comment]
s = from.dup
s = s.gsub(/YOU are/,"I'M")
s = s.gsub(/You're/,"I'm")
s = s.gsub(/you /i,"I ")
s = s.gsub(/your/i,"my")

Maybe I should work on this some more?

**Comment by brianburridge** [comment]
@tomwill1701 everything looks good. :+1: 

Two suggestions for you as alternate solutions:

on line 5 of a9.rb, try this code:

    puts a.join("/")

For line 52, consider this code:

    s =~ /\bfoot\b/

**Comment by tomwill1701** [comment]
Join in great:

join(separator=$,) → str click to toggle source
Returns a string created by converting each element of the array to a string, separated by the given separator. If the separator is nil, it uses current $,. If both the separator and $, are nil, it uses empty string.

Do all my string have \n in them?  Not sure how to continue a string on the next line of the editor?

**Comment by brianburridge** [comment]
I'm not sure what you are asking. I don't see any extra \n's.

**Comment by tomwill1701** [comment]
s = "this
is
a
string"

as opposed to 

s = "this is a string"

**Comment by tomwill1701** [comment]
Now that I think about it I am sure it is ok.  Just white space

**Comment by brianburridge** [comment]
I see. So yes, if you put a line feed inside a string in your code, then that linefeed will be in the string. All depends on if you want those line breaks in your string. I probably don't usually do that and would simply not force the wrapping in my editor so that I don't end up with forced breaks wherever I save the string (database) or output it.

**Comment by tomwill1701** [comment]
OK...Just not easy to read sometimes
